language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - yarn install
        - docker run --name snt-test-db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=snt-test-db -d postgres
      script: yarn test --coverage
    - stage: Build
      name: Compiling TypeScript
      script: yarn build
