language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - docker run --name snt-test-db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -d postgres
        - docker run --name snt-redis-session -d redis
      script: yarn test --coverage
    - stage: Build
      name: Compiling TypeScript
      before_script:
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        # Add gcloud to $PATH
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
        - yarn build
      script:
        - docker build -t snt-gql .
