language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
  yarn: true
notifications:
  email: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - docker run --name snt-test-db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -d postgres
        - docker run --name snt-redis-session -d redis
      script: yarn test --coverage
    - stage: Build
      name: Compiling TypeScript
      before_script:
        - gcloud version || true
        # - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        # - source /home/travis/google-cloud-sdk/path.bash.inc
        - openssl aes-256-cbc -K $encrypted_752465ee0773_key -iv $encrypted_752465ee0773_iv -in travis.json.enc -out ./gcloud.json -d
        - gcloud auth activate-service-account --key-file ./gcloud.json
        - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
        - yarn build
      script:
        - docker build -t snt-gql .
      after_script:
        - docker tag snt-gql eu.gcr.io/sentad-221009/snt-gql
        - bash -c "docker tag snt-gql eu.gcr.io/sentad-221009/snt-gql:$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g'| tr -d '[[:space:]]')"
        - docker push eu.gcr.io/sentad-221009/snt-gql
        - export SNT_ENV=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }'
        # - bash -c "docker push eu.gcr.io/sentad-221009/snt-gql:$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g'| tr -d '[[:space:]]')"
