language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - yarn install
      script: yarn test --coverage
    - stage: Build
      name: Compiling TypeScript
      script: yarn build
